export default [
	[15, "Javascript"],
	[13, "CSS3"],
	[12, "HTML5"],
	[8, "Git"],
	[6, "Vue.js"],
	[5, "Python"],
	[4, "Travis CI"],
	[4, "PHP"],
	[3, "Arduino"],
	[3, "Service Worker"],
	[2, "Wordpress"],
	[1, "BricxCC"],
	[1, "SQL"],
	[1, "PCB Design"],
	[1, "CNC milling"],
	[1, "laser cutting"],
	[1, "Squeak"],
	[1, "React"],
	[1, "Gimp"],
	[1, "Adobe XD"],
	[1, "Firebase Firestore"],
	[1, "NPM"],
	[1, "FeathersJS"],
	[1, "Angular 1"],
	[1, "BrixCC"],
];
