export default [
	[15, "Javascript"],
	[10, "CSS3"],
	[10, "HTML5"],
	[8, "GitHub"],
	[6, "Vue.js"],
	[6, "Python"],
	[4, "CI/CD Pipelines"],
	[4, "Firebase"],
	[3, "NPM"],
	[4, "React"],
	[3, "Arduino"],
	[3, "PHP"],
	// [3, "Service Worker"],
	[2, "Wordpress"],
	[2, "Docker"],
	[1, "SQL"],
	// [1, "PCB Design"],
	// [1, "CNC Milling"],
	// [1, "Laser Cutting"],
	// [1, "Image Editing"],
	[1, "UX Design"],
	[1, "ExpressJS"],
	[1, "Angular"],
	[1, "C++"],
];
