export default [
	[15, "Javascript"],
	[10, "CSS3"],
	[10, "HTML5"],
	[8, "GitHub"],
	[6, "Vue.js"],
	[6, "Python"],
	[4, "CI/CD Pipelines"],
	[4, "Firebase"],
	[4, "PHP"],
	[3, "Arduino"],
	[3, "Service Worker"],
	[2, "Wordpress"],
	[2, "React"],
	[1, "SQL"],
	[1, "PCB Design"],
	[1, "CNC Milling"],
	[1, "Laser Cutting"],
	[1, "Image Editing"],
	[1, "Adobe XD"],
	[1, "NPM"],
	[1, "ExpressJS"],
	[1, "Angular"],
];
